//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secure.SecurityDatabaseSync.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Secure.SecurityDatabaseSync.UI.Resources.MessageResource", typeof(MessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --default, --bulk, --hard-bulk, --quit.
        /// </summary>
        internal static string CommandAvailableList {
            get {
                return ResourceManager.GetString("CommandAvailableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Command completed successfully!.
        /// </summary>
        internal static string CommandCompleted {
            get {
                return ResourceManager.GetString("CommandCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing command..
        /// </summary>
        internal static string CommandError {
            get {
                return ResourceManager.GetString("CommandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Command failed!.
        /// </summary>
        internal static string CommandFailed {
            get {
                return ResourceManager.GetString("CommandFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Invalid command entered. Try it again!.
        /// </summary>
        internal static string CommandInvalid {
            get {
                return ResourceManager.GetString("CommandInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter database code (field): .
        /// </summary>
        internal static string EnterDatabaseCode {
            get {
                return ResourceManager.GetString("EnterDatabaseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter source database name: .
        /// </summary>
        internal static string EnterDatabaseNameSource {
            get {
                return ResourceManager.GetString("EnterDatabaseNameSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter target database name: .
        /// </summary>
        internal static string EnterDatabaseNameTarget {
            get {
                return ResourceManager.GetString("EnterDatabaseNameTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter sync type: .
        /// </summary>
        internal static string EnterSyncType {
            get {
                return ResourceManager.GetString("EnterSyncType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code.
        /// </summary>
        internal static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid source database.
        /// </summary>
        internal static string InvalidDatabaseSource {
            get {
                return ResourceManager.GetString("InvalidDatabaseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target database.
        /// </summary>
        internal static string InvalidDatabaseTarget {
            get {
                return ResourceManager.GetString("InvalidDatabaseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid synchronization type.
        /// </summary>
        internal static string InvalidSyncType {
            get {
                return ResourceManager.GetString("InvalidSyncType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        internal static string ParamCode {
            get {
                return ResourceManager.GetString("ParamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sourceDb.
        /// </summary>
        internal static string ParamSourceDb {
            get {
                return ResourceManager.GetString("ParamSourceDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncType.
        /// </summary>
        internal static string ParamSyncType {
            get {
                return ResourceManager.GetString("ParamSyncType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to targetDb.
        /// </summary>
        internal static string ParamTargetDb {
            get {
                return ResourceManager.GetString("ParamTargetDb", resourceCulture);
            }
        }
    }
}
